name: Health check

on:
  schedule:
    - cron: '00 12 * * 1'

jobs:
  check_deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping pokedex
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://hyfsp11-pokedex-simoj.fly.dev/health
          max-attempts: 2
          retry-delay: 5s
