name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: true
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test the code
        run: npm run test
      - name: e2e test with Cypress
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Fly Deploy
        if: ${{ github.event_name == 'push'  &&  !contains(toJson(github.event.commits.*.message), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Discord Webhook Notify info
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ success() }}
        with:
          severity: info
          description: Deploy succesful!
          details: https://hyfsp11-pokedex-simoj.fly.dev/
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord Webhook Notify error
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: tag_release
        if: ${{ github.event_name == 'push' &&  !contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

